name: mayo_flutter_permissions
description: Package for requesting permissions on Flutter
version: 0.0.11
homepage: https://mayosoftware.es

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  device_info_plus: ^11.2.1

  flutter:
    sdk: flutter

  geolocator: ^14.0.1
  image_picker: ^1.0.4

  file_picker: ^10.2.0

  location: ^7.0.0

  permission_handler: ^12.0.0+1

dev_dependencies:
  build_runner: ^2.1.5
  firebase_storage_mocks: ^0.7.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.1.2
  very_good_analysis: ^9.0.0